//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pubs.WCFPubs {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleUsuario", Namespace="http://schemas.datacontract.org/2004/07/WcfSPubs.Fachada")]
    [System.SerializableAttribute()]
    public partial class DetalleUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsAdmin {
            get {
                return this.EsAdminField;
            }
            set {
                if ((this.EsAdminField.Equals(value) != true)) {
                    this.EsAdminField = value;
                    this.RaisePropertyChanged("EsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFPubs.IServicePubs")]
    public interface IServicePubs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePubs/ValidaUsuario", ReplyAction="http://tempuri.org/IServicePubs/ValidaUsuarioResponse")]
        Pubs.WCFPubs.DetalleUsuario[] ValidaUsuario(string Usuario, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePubs/ValidaUsuario", ReplyAction="http://tempuri.org/IServicePubs/ValidaUsuarioResponse")]
        System.Threading.Tasks.Task<Pubs.WCFPubs.DetalleUsuario[]> ValidaUsuarioAsync(string Usuario, string Contrasena);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePubsChannel : Pubs.WCFPubs.IServicePubs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePubsClient : System.ServiceModel.ClientBase<Pubs.WCFPubs.IServicePubs>, Pubs.WCFPubs.IServicePubs {
        
        public ServicePubsClient() {
        }
        
        public ServicePubsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePubsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePubsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePubsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pubs.WCFPubs.DetalleUsuario[] ValidaUsuario(string Usuario, string Contrasena) {
            return base.Channel.ValidaUsuario(Usuario, Contrasena);
        }
        
        public System.Threading.Tasks.Task<Pubs.WCFPubs.DetalleUsuario[]> ValidaUsuarioAsync(string Usuario, string Contrasena) {
            return base.Channel.ValidaUsuarioAsync(Usuario, Contrasena);
        }
    }
}
